# Generated by Django 4.2.6 on 2023-10-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
